### ISSUE TITLE
How to get phased genotypes of parents?

### ISSUE THREAD

**Issue by xiekunwhy** [alethere/SmoothDescent#2]
Hi,

For F1 populations, in many cases (genotype by sequencing or snp chip), we only get unphased genotypes of parents an how to phase parents' genotypes to feed SmoothDescent?

For example, how to convert lmxll nnxnp hkxhk markers to SmoothDescent format?

Best,
Kun

**Comment by alethere** [comment]
Hi Kun,

If I'm not mistaken that's the notation of JoinMap. For each marker, there should be a clear conversion between the JoinMap notation and a phased genetic map. For example:

lm x ll = parent 1 dosage 1, parent 2 dosage 0 = [0,1,0,0] or [1,0,0,0]
nn x np = p1 dosage 0, p2 dosage 1 = [0,0,0,1] or [0,0,1,0]

I'm not very familiar with JoinMap but I think depending on the letters used you can distinguish between each phasing (so between [1,0,0,0] and [0,1,0,0]). Once you have that translation table, it's just a matter of turning your phased map column into a matrix of 0s and 1s. 

Hope this helps,
Ale

**Comment by xiekunwhy** [comment]
Dear Ale,

Yes, I am now use JoinMap like genotype code, and I also have vcf file.

I am trying to translate my genotype file to SmoothDescent input files, but I really don't know how to do that.
1) SmoothDescent accept updog genotype files only? So I need to run updog first?
2) In marker order file, position column means what? Genetic position? May I use physical instead?
3) A small vcf and txt file including some markers were attached following (diploid F1 ppopulation, P137 is father and P409 is mother, others are F1 progeny), would you please show me how to translate these marker sites to SmoothDescent input files? Thank you very much!
[test.zip](https://github.com/alethere/SmoothDescent/files/9982868/test.zip)

By the way, when I install the vignette, I got following errors (mfrow value are not right in SmoothDescent_vignette.Rmd).
![image](https://user-images.githubusercontent.com/17738229/201153254-7037c931-f001-4d23-9964-e75afbcc4b25.png)

Best regards,
Kun

**Comment by alethere** [comment]
Hi Kun,

To answer your questions:
1. No you don't need to run updog first, just need to provide a genotype dosage matrix (with values 0, 1, 2...). Have a look at the vignette to see the type of input needed.
2. Yes, position means genetic position. You can also use physical position, but then make sure to adjust the parameter `prediction_interval` to a larger value. Normally it's 10cM, so in physical units I would suggest that you use 10.000.000 bp as the `prediction_interval`.
3. I'll see what I can do but I'm quite busy at the moment so I don't know when I'll find time for this.

Thanks for spotting the bug, should be fixed already. If you run `devtools::install_github("https://github.com/alethere/SmoothDescent", build_vignette = T)` you should get no errors now.

Regards,
Alejandro

**Comment by xiekunwhy** [comment]
Hi Alejandro,

Thank you for your reply, I think I know how to covert my genotypes to SmoothDescent inputs now, I think you mean "allele dosage" when saying "genotype dosage".

Best,
Kun

**Comment by alethere** [comment]
Yes indeed, allele dosage is what I mean. Glad to hear you're getting to work. I'll close the issue then.

Regards,
Alejandro
